// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonMenu: typeof import('~icons/carbon/menu')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    UilGithub: typeof import('~icons/uil/github')['default']
    UilInstagram: typeof import('~icons/uil/instagram')['default']
    UilTelegram: typeof import('~icons/uil/telegram')['default']
    UilTwitter: typeof import('~icons/uil/twitter')['default']
  }
}

export { }
